# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
#  - name: Featured Projects
#    submenu:
#      - name: MicroBam
#        link: /projects/microbam
#      - name: OurLegacy
#        link: /projects/ourlegacy
  - name: Blog
    link: /
  - name: Etiketler
    link: /tags
  - name: Hakkımda
    link: /about
  - name: Beni Takip Et
    submenu:
      - name: GitHub
        icon: github
        link: https://github.com/melihKucuk
      - name: LinkedIn
        icon: linkedin-square
        link: https://www.linkedin.com/in/melih-k%C3%BC%C3%A7%C3%BCk-872b63201/
#      - name: Twitter
#        icon: twitter
#        link: https://twitter.com/koint
      - name: Instagram
        icon: instagram
        link: https://www.instagram.com/mlhkck1912/
    
